# fly.toml app configuration file generated for tent-service on 2026-02-22T00:48:47-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tent-service'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_NAME = 'TentService'
  DEBUG = 'false'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
